[package]
name = "whale-c"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
ir = { git = "https://github.com/wavefnd/Whale.git", branch = "master", package = "ir", features = ["socket"]}